typography_spectrum: 0.50994
color:
  brandColors:
    - '#d5dce2'
    - '#c9ab91'
    - '#6d4f3c'
    - '#26252b'
    - '#cb4c57'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: ChristianCampo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: christian campo
    url: 'http://www.christiancampo.de'
    type: external
favicon: null
title: Christian Campo
purpose: []
