name: ChristianCampo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.64594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070b0c'
    - '#3d3f4c'
    - '#d1959e'
    - '#6cabc9'
    - '#fa5c4d'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
