name: Christian Campo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50994
navigation:
  - name: christian campo
    url: 'http://www.christiancampo.de'
    type: external
title: Christian Campo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5dce2'
    - '#c9ab91'
    - '#6d4f3c'
    - '#26252b'
    - '#cb4c57'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
