name: ChristianCampo
favicon: null
layout_spectrum: 0.906767914770171
typography_spectrum: 0.19510330958291888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.29461530433036387
  lightness: 0.3065281333401799
  saturation: 0.09569817990995944
  rhythmicContrast: 0.5898496713489294
purpose: []
